appname="功德增加"
appver="1.0"
appcode="1"
appsdk="15"
path_pattern=""
packagename="com.nal.Buddhism.love"
theme="Theme_DeviceDefault"
app_key=""
app_channel=""
developer=""
description=""
debugmode=true
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
